version: '3.8'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ducksfinances
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      bash -c "
        python -m flask db upgrade
        && python -m flask run --host=0.0.0.0 --port=5000
      "
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ducksfinances
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=dev-secret-key
      - JWT_SECRET_KEY=dev-jwt-secret-key
    depends_on:
      - db
      - redis
    networks:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
